version: "2.2"

volumes:
    volume-mysql:
    volume-elasticsearch:
    volume-rabbitmq-data:
    volume-rabbitmq-log:
networks:
  local-nextwork:
services:
  watchmoviegn-gateway:
    container_name: watchmoviegn-gateway
    build: 
      context: ..\WatchMovieGN-BE\WatchMovieGN-GateWay
      dockerfile: Dockerfile
    image: gaonet567/watchmoviegn-gateway
    networks:
      - local-nextwork
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
      - mysql
      - rabbitmq
  watchmoviegn-movie:
    container_name: watchmoviegn-movie
    build:
      context: ..\WatchMovieGN-BE\WatchMovieGN-Movie
      dockerfile: Dockerfile
    image: gaonet567/watchmoviegn-movie
    networks:
      - local-nextwork
    ports:
      - 8081:8081
    depends_on:
      - watchmoviegn-gateway
  watchmoviegn-search:
    container_name: watchmoviegn-search
    build:
      context: ..\WatchMovieGN-BE\WatchMovieGN-Search
      dockerfile: Dockerfile
    image: gaonet567/watchmoviegn-movie
    networks:
      - local-nextwork
    ports:
      - 8084:8084
    depends_on:
      - watchmoviegn-gateway
  watchmoviegn-admin:
    container_name: watchmoviegn-admin
    image: gaonet567/watchmoviegn-admin
    networks:
      - local-nextwork
    ports:
      - 3000:3000
    depends_on:
    - watchmoviegn-movie
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    volumes:
      - volume-mysql:/var/lib/mysql
    networks:
      - local-nextwork
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_USER: watchmoviegn
      MYSQL_PASSWORD: watchmoviegn
      MYSQL_DATABASE: watchmoviegn
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - local-nextwork
    ports:
      - 9200:9200
    volumes:
      - volume-elasticsearch:/usr/share/elasticsearch/config/certs
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.9.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - local-nextwork
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - volume-rabbitmq-data:/var/lib/rabbitmq/
        - volume-rabbitmq-log:/var/log/rabbitmq
    networks:
        - local-nextwork
  