#Spring cloud
spring:
  application:
    name: @project.artifactId@
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
  main:
    web-application-type: reactive
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8999