package watch.movie.gn.enums;

import lombok.Getter;

@Getter
public enum CountryEnum {
	NETHERLANDS(1, "NL", "Netherlands"), CURAÇAO(2, "CW", "Curaçao"), THAILAND(3, "TH", "Thailand"),
	AMERICAN_SAMOA(4, "AS", "American Samoa"), LIBYA(5, "LY", "Libya"), KUWAIT(6, "KW", "Kuwait"),
	ICELAND(7, "IS", "Iceland"), MICRONESIA(8, "FM", "Micronesia"), BELGIUM(9, "BE", "Belgium"),
	RUSSIA(10, "RU", "Russia"), CONGO_BRAZZAVILLE(11, "CG", "Congo - Brazzaville"),
	LIECHTENSTEIN(12, "LI", "Liechtenstein"), NORTH_MACEDONIA(13, "MK", "North Macedonia"), JERSEY(14, "JE", "Jersey"),
	KYRGYZSTAN(15, "KG", "Kyrgyzstan"), CHRISTMAS_ISLAND(16, "CX", "Christmas Island"), ALGERIA(17, "DZ", "Algeria"),
	RÉUNION(18, "RE", "Réunion"), AUSTRIA(19, "AT", "Austria"), BOUVET_ISLAND(20, "BV", "Bouvet Island"),
	SINGAPORE(21, "SG", "Singapore"), PANAMA(22, "PA", "Panama"), ITALY(23, "IT", "Italy"),
	GUADELOUPE(24, "GP", "Guadeloupe"), CROATIA(25, "HR", "Croatia"), SWITZERLAND(26, "CH", "Switzerland"),
	SINT_MAARTEN(27, "SX", "Sint Maarten"), DJIBOUTI(28, "DJ", "Djibouti"), TANZANIA(29, "TZ", "Tanzania"),
	ANDORRA(30, "AD", "Andorra"), BURKINA_FASO(31, "BF", "Burkina Faso"), PUERTO_RICO(32, "PR", "Puerto Rico"),
	MALI(33, "ML", "Mali"), CAMBODIA(34, "KH", "Cambodia"), INDONESIA(35, "ID", "Indonesia"),
	MAYOTTE(36, "YT", "Mayotte"), VIETNAM(37, "VN", "Vietnam"), BOTSWANA(38, "BW", "Botswana"),
	ST_HELENA(39, "SH", "St. Helena"), CYPRUS(40, "CY", "Cyprus"), TAJIKISTAN(41, "TJ", "Tajikistan"),
	AUSTRALIA(42, "AU", "Australia"), CAYMAN_ISLANDS(43, "KY", "Cayman Islands"),
	FAROE_ISLANDS(44, "FO", "Faroe Islands"), EQUATORIAL_GUINEA(45, "GQ", "Equatorial Guinea"),
	DENMARK(46, "DK", "Denmark"), BULGARIA(47, "BG", "Bulgaria"), RWANDA(48, "RW", "Rwanda"),
	COTE_D_IVOIRE(49, "CI", "Côte d’Ivoire"), SYRIA(50, "SY", "Syria"),
	UNITED_ARAB_EMIRATES(51, "AE", "United Arab Emirates"),
	PALESTINIAN_TERRITORIES(52, "PS", "Palestinian Territories"), NORWAY(53, "NO", "Norway"),
	SRI_LANKA(54, "LK", "Sri Lanka"), MYANMAR_BURMA(55, "MM", "Myanmar (Burma)"), ZIMBABWE(56, "ZW", "Zimbabwe"),
	KIRIBATI(57, "KI", "Kiribati"), IRELAND(58, "IE", "Ireland"), GABON(59, "GA", "Gabon"),
	CZECHIA(60, "CZ", "Czechia"), TOKELAU(61, "TK", "Tokelau"), US_OUTLYING_ISLANDS(62, "UM", "U.S. Outlying Islands"),
	SLOVENIA(63, "SI", "Slovenia"), KAZAKHSTAN(64, "KZ", "Kazakhstan"), GREECE(65, "GR", "Greece"),
	HAITI(66, "HT", "Haiti"), YEMEN(67, "YE", "Yemen"), ESWATINI(68, "SZ", "Eswatini"),
	AFGHANISTAN(69, "AF", "Afghanistan"), BAHRAIN(70, "BH", "Bahrain"), PORTUGAL(71, "PT", "Portugal"),
	MONGOLIA(72, "MN", "Mongolia"), NEPAL(73, "NP", "Nepal"), UNITED_KINGDOM(74, "GB", "United Kingdom"),
	BELARUS(75, "BY", "Belarus"), SVALBARD_JAN_MAYEN(76, "SJ", "Svalbard & Jan Mayen"),
	TIMORLESTE(77, "TL", "Timor-Leste"), ARUBA(78, "AW", "Aruba"), HUNGARY(79, "HU", "Hungary"),
	SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS(80, "GS", "South Georgia & South Sandwich Islands"),
	DOMINICA(81, "DM", "Dominica"), BURUNDI(82, "BI", "Burundi"), COOK_ISLANDS(83, "CK", "Cook Islands"),
	ANTIGUA_BARBUDA(84, "AG", "Antigua & Barbuda"), MACAO_SAR_CHINA(85, "MO", "Macao SAR China"),
	SAMOA(86, "WS", "Samoa"), TURKMENISTAN(87, "TM", "Turkmenistan"), ÅLAND_ISLANDS(88, "AX", "Åland Islands"),
	BELIZE(89, "BZ", "Belize"), SLOVAKIA(90, "SK", "Slovakia"), PERU(91, "PE", "Peru"), NAMIBIA(92, "NA", "Namibia"),
	GUATEMALA(93, "GT", "Guatemala"), VATICAN_CITY(94, "VA", "Vatican City"), FRANCE(95, "FR", "France"),
	CHILE(96, "CL", "Chile"), BENIN(97, "BJ", "Benin"), NORTHERN_MARIANA_ISLANDS(98, "MP", "Northern Mariana Islands"),
	NAURU(99, "NR", "Nauru"), GRENADA(100, "GD", "Grenada"), SIERRA_LEONE(101, "SL", "Sierra Leone"),
	TUNISIA(102, "TN", "Tunisia"), FRENCH_POLYNESIA(103, "PF", "French Polynesia"), GUAM(104, "GU", "Guam"),
	DOMINICAN_REPUBLIC(105, "DO", "Dominican Republic"), CAMEROON(106, "CM", "Cameroon"),
	ANGUILLA(107, "AI", "Anguilla"), PALAU(108, "PW", "Palau"), MARTINIQUE(109, "MQ", "Martinique"),
	COMOROS(110, "KM", "Comoros"), GEORGIA(111, "GE", "Georgia"), TONGA(112, "TO", "Tonga"),
	AZERBAIJAN(113, "AZ", "Azerbaijan"), SAN_MARINO(114, "SM", "San Marino"),
	PAPUA_NEW_GUINEA(115, "PG", "Papua New Guinea"), NEW_CALEDONIA(116, "NC", "New Caledonia"),
	MOROCCO(117, "MA", "Morocco"), ERITREA(118, "ER", "Eritrea"),
	ST_VINCENT_GRENADINES(119, "VC", "St. Vincent & Grenadines"), CHINA(120, "CN", "China"),
	UKRAINE(121, "UA", "Ukraine"), ST_BARTHÉLEMY(122, "BL", "St. Barthélemy"), MAURITANIA(123, "MR", "Mauritania"),
	ST_KITTS_NEVIS(124, "KN", "St. Kitts & Nevis"), FRENCH_GUIANA(125, "GF", "French Guiana"),
	SENEGAL(126, "SN", "Senegal"), PHILIPPINES(127, "PH", "Philippines"), WALLIS_FUTUNA(128, "WF", "Wallis & Futuna"),
	GUINEABISSAU(129, "GW", "Guinea-Bissau"), SPAIN(130, "ES", "Spain"), BERMUDA(131, "BM", "Bermuda"),
	COLOMBIA(132, "CO", "Colombia"), PARAGUAY(133, "PY", "Paraguay"), NIUE(134, "NU", "Niue"),
	MONTSERRAT(135, "MS", "Montserrat"), JAMAICA(136, "JM", "Jamaica"), VANUATU(137, "VU", "Vanuatu"),
	GUERNSEY(138, "GG", "Guernsey"), ECUADOR(139, "EC", "Ecuador"), UNITED_STATES(140, "US", "United States"),
	SOMALIA(141, "SO", "Somalia"), NIGER(142, "NE", "Niger"), LAOS(143, "LA", "Laos"), MONACO(144, "MC", "Monaco"),
	ZAMBIA(145, "ZM", "Zambia"), ETHIOPIA(146, "ET", "Ethiopia"), VENEZUELA(147, "VE", "Venezuela"),
	ALBANIA(148, "AL", "Albania"), BRUNEI(149, "BN", "Brunei"), MALTA(150, "MT", "Malta"),
	NORTH_KOREA(151, "KP", "North Korea"), LIBERIA(152, "LR", "Liberia"), ISRAEL(153, "IL", "Israel"),
	GHANA(154, "GH", "Ghana"), TURKEY(155, "TR", "Turkey"), MOLDOVA(156, "MD", "Moldova"),
	NORFOLK_ISLAND(157, "NF", "Norfolk Island"), LEBANON(158, "LB", "Lebanon"), GUYANA(159, "GY", "Guyana"),
	BOLIVIA(160, "BO", "Bolivia"), ARMENIA(161, "AM", "Armenia"), LESOTHO(162, "LS", "Lesotho"),
	MAURITIUS(163, "MU", "Mauritius"), JORDAN(164, "JO", "Jordan"),
	HONG_KONG_SAR_CHINA(165, "HK", "Hong Kong SAR China"), ISLE_OF_MAN(166, "IM", "Isle of Man"),
	GIBRALTAR(167, "GI", "Gibraltar"), ESTONIA(168, "EE", "Estonia"), ROMANIA(169, "RO", "Romania"),
	CANADA(170, "CA", "Canada"), PAKISTAN(171, "PK", "Pakistan"), NIGERIA(172, "NG", "Nigeria"),
	ST_LUCIA(173, "LC", "St. Lucia"), MONTENEGRO(174, "ME", "Montenegro"),
	BRITISH_VIRGIN_ISLANDS(175, "VG", "British Virgin Islands"), COSTA_RICA(176, "CR", "Costa Rica"),
	TURKS_CAICOS_ISLANDS(177, "TC", "Turks & Caicos Islands"), SAUDI_ARABIA(178, "SA", "Saudi Arabia"),
	MALDIVES(179, "MV", "Maldives"), SOUTH_KOREA(180, "KR", "South Korea"), LITHUANIA(181, "LT", "Lithuania"),
	INDIA(182, "IN", "India"), JAPAN(183, "JP", "Japan"), SURINAME(184, "SR", "Suriname"),
	TRINIDAD_TOBAGO(185, "TT", "Trinidad & Tobago"), POLAND(186, "PL", "Poland"), ST_MARTIN(187, "MF", "St. Martin"),
	CARIBBEAN_NETHERLANDS(188, "BQ", "Caribbean Netherlands"), SOLOMON_ISLANDS(189, "SB", "Solomon Islands"),
	CHAD(190, "TD", "Chad"), ANGOLA(191, "AO", "Angola"), LUXEMBOURG(192, "LU", "Luxembourg"),
	MALAWI(193, "MW", "Malawi"), HEARD_MCDONALD_ISLANDS(194, "HM", "Heard & McDonald Islands"),
	BRITISH_INDIAN_OCEAN_TERRITORY(195, "IO", "British Indian Ocean Territory"), FINLAND(196, "FI", "Finland"),
	GERMANY(197, "DE", "Germany"), EGYPT(198, "EG", "Egypt"), BOSNIA_HERZEGOVINA(199, "BA", "Bosnia & Herzegovina"),
	COCOS_KEELING_ISLANDS(200, "CC", "Cocos (Keeling) Islands"), SOUTH_SUDAN(201, "SS", "South Sudan"),
	ST_PIERRE_MIQUELON(202, "PM", "St. Pierre & Miquelon"), NICARAGUA(203, "NI", "Nicaragua"),
	MADAGASCAR(204, "MG", "Madagascar"), US_VIRGIN_ISLANDS(205, "VI", "U.S. Virgin Islands"),
	UGANDA(206, "UG", "Uganda"), BRAZIL(207, "BR", "Brazil"), SEYCHELLES(208, "SC", "Seychelles"),
	MEXICO(209, "MX", "Mexico"), NEW_ZEALAND(210, "NZ", "New Zealand"), LATVIA(211, "LV", "Latvia"),
	SOUTH_AFRICA(212, "ZA", "South Africa"), GREENLAND(213, "GL", "Greenland"), HONDURAS(214, "HN", "Honduras"),
	WESTERN_SAHARA(215, "EH", "Western Sahara"), FIJI(216, "FJ", "Fiji"), CONGO_KINSHASA(217, "CD", "Congo - Kinshasa"),
	SÃO_TOMÉ_PRÍNCIPE(218, "ST", "São Tomé & Príncipe"), TUVALU(219, "TV", "Tuvalu"), BARBADOS(220, "BB", "Barbados"),
	PITCAIRN_ISLANDS(221, "PN", "Pitcairn Islands"), MARSHALL_ISLANDS(222, "MH", "Marshall Islands"),
	BAHAMAS(223, "BS", "Bahamas"), SUDAN(224, "SD", "Sudan"), CUBA(225, "CU", "Cuba"),
	FRENCH_SOUTHERN_TERRITORIES(226, "TF", "French Southern Territories"), ANTARCTICA(227, "AQ", "Antarctica"),
	MALAYSIA(228, "MY", "Malaysia"), IRAQ(229, "IQ", "Iraq"), FALKLAND_ISLANDS(230, "FK", "Falkland Islands"),
	GAMBIA(231, "GM", "Gambia"), TAIWAN(232, "TW", "Taiwan"), URUGUAY(233, "UY", "Uruguay"),
	SERBIA(234, "RS", "Serbia"), OMAN(235, "OM", "Oman"), KENYA(236, "KE", "Kenya"),
	CAPE_VERDE(237, "CV", "Cape Verde"), TOGO(238, "TG", "Togo"), ARGENTINA(239, "AR", "Argentina"),
	BHUTAN(240, "BT", "Bhutan"), SWEDEN(241, "SE", "Sweden"), QATAR(242, "QA", "Qatar"),
	MOZAMBIQUE(243, "MZ", "Mozambique"), IRAN(244, "IR", "Iran"), GUINEA(245, "GN", "Guinea"),
	UZBEKISTAN(246, "UZ", "Uzbekistan"), CENTRAL_AFRICAN_REPUBLIC(247, "CF", "Central African Republic"),
	EL_SALVADOR(248, "SV", "El Salvador"), BANGLADESH(249, "BD", "Bangladesh");

	private Integer pkIdCountry;
	private String code;
	private String name;

	private CountryEnum(Integer pkIdCountry, String code, String name) {
		this.pkIdCountry = pkIdCountry;
		this.code = code;
		this.name = name;
	}

}
