version: "2.2"

volumes:
    volume-mysql:
    volume-elasticsearch:
networks:
  local-nextwork:
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    volumes:
      - volume-mysql:/var/lib/mysql
    networks:
      - local-nextwork
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_USER: watchmoviegn
      MYSQL_PASSWORD: watchmoviegn
      MYSQL_DATABASE: watchmoviegn
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - local-nextwork
    ports:
      - 9200:9200
    volumes:
      - volume-elasticsearch:/usr/share/elasticsearch/config/certs
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.9.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - local-nextwork
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601